ARG BUILDER=riderlty/fontinass-builder:hashval
FROM ${BUILDER} AS cache
FROM python:3.10-slim-bookworm
COPY onlineFonts.json run.sh requirements.txt /
COPY src /src/
COPY --from=cache /wheels /wheels
COPY --from=cache /app/src/py2cy/* /app/src/py2cy/
RUN chmod 777 /run.sh && pip install --no-cache --find-links /wheels -r /requirements.txt  && rm -rf /wheels && mkdir /data
CMD ["/bin/sh" , "-c" , "/run.sh"]
