name: build-builder-multiarch
on:
  workflow_dispatch:
  push:
    paths:
      - requirements.txt
      - src/py2cy/c_utils.pyx
      - src/py2cy/cpp_utils.cpp
      - src/py2cy/setup.py
      - src/subset/**
      
jobs:
  build-arm64:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build-arm64
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-builder
          context: .
          push: true
          tags: |
            riderlty/fontinass-builder:latest-arm64
      
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     
      - name: build-amd64
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile-builder
          context: .
          push: true
          tags: |
            riderlty/fontinass-builder:latest-amd64

  combine-two-images:
    runs-on: ubuntu-latest
    needs:
      - build-arm64
      - build-amd64
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@master # or use a pinned version in the Releases tab
        with:
            inputs: riderlty/fontinass-builder:latest-amd64,riderlty/fontinass-builder:latest-arm64
            tags: riderlty/fontinass-builder:latest
            push: true
